{% set name = "lifelines" %}
{% set version = "0.30.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3d474c138d941f48c3b7a7b116b35823ab90e303e09b6f1e9a01e982a5f9e671

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.14.0
    - scipy >=1.7.0
    - pandas >=2.1
    - matplotlib-base >=3.0
    - autograd >=1.5
    - autograd-gamma >=0.3
    - formulaic >=0.2.2

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils
  requires: 
    - pip
  commands: 
    - pip check

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  dev_url: https://github.com/CamDavidsonPilon/lifelines
  doc_url: https://lifelines.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: lifelines is a complete survival analysis library, written in pure Python. 
  description: lifelines is a complete survival analysis library, written in pure Python.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
