{% set name = "lifelines" %}


{% set version = "0.23.6" %}
{% set sha256 = "3088be935cc3556194197073ed350ebcd7212740b516dd9b8b019385ed715700" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.0
    - pandas >=0.23.0
    - matplotlib >=3.0
    - autograd >=1.3
    - autograd-gamma >=0.3

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: 'Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
