{% set name = "lifelines" %}
{% set version = "0.17.0" %}
{% set sha256 = "05d5d8cebff45cd61f9809812481c33863c9040aab63ef38d74331a50c1ec5cc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas >=0.18
    - matplotlib >=2.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: 'Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
