{% set name = "lifelines" %}
{% set version = "0.13.0" %}
{% set sha256 = '606eefb1d9ac07c2fa98a214fe18bc0fdaf9cd5c0f8d34eb084705efb3c36bcd' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pandas >=0.18
    - matplotlib >=2.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: 'Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
