{% set name = "lifelines" %}


{% set version = "0.24.1" %}
{% set sha256 = "9167b59455f57b1944dfb3e504d1eff0f6b3c83199d651b1f988826175e41068" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.0
    - pandas >=0.23.0
    - matplotlib-base >=3.0
    - autograd >=1.3
    - autograd-gamma >=0.3

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
