{% set name = "lifelines" %}


{% set version = "0.27.0" %}
{% set sha256 = "1d88e7b532f8be820244f23f97b4f9ab404bc7c25d354486c48b9fd3244beb03" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.6
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.2
    - pandas >=1.0.0
    - matplotlib-base >=3.0
    - autograd >=1.3
    - autograd-gamma >=0.3
    - formulaic >=0.2.2

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
