{% set name = "lifelines" %}

{% set version = "0.20.0" %}
{% set sha256 = "f430a873d51187f95934dbb41cd7ea0c76e322ced6af4c5f44c14087509730c5" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.0
    - pandas >=0.20
    - matplotlib >=2.0
    - autograd >=1.2
    - bottleneck >=1.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: 'Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
