{% set name = "lifelines" %}


{% set version = "0.25.3" %}
{% set sha256 = "3331eaf0a3e3f52995236672a5bd1491b10c9704cb817a1b9ab5ed0be6e760aa" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/CamDavidsonPilon/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - setuptools
    - numpy >=1.14.0
    - scipy >=1.2
    - pandas >=0.23.0
    - matplotlib-base >=3.0
    - autograd >=1.3
    - autograd-gamma >=0.3
    - patsy >=0.5.0

test:
  imports:
    - lifelines
    - lifelines.datasets
    - lifelines.fitters
    - lifelines.utils

about:
  home: https://github.com/CamDavidsonPilon/lifelines
  license: MIT
  license_file: LICENSE
  summary: Survival analysis in Python, including Kaplan Meier, Nelson Aalen and regression

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
