travis:
  secure:
    BINSTAR_TOKEN: BvlA/B+Iali79nOm5R4Cd3569wMfshHnFcR2442s2cKnHtD4pcYgUmf9OrQVcTtYsDEFqcDVmjTI5GGgwZluAEZFdF98soSMsIQtfvfTgwhkVKemI+gxPmQKUzaJ1DpjQT7kZ21XKQrzMi1tKWb1KxBShlB8AyRibMVLMSomRjIHAg7r6+hp7Km6wxu7pS8FG9S2DOpnoxlYxTbgnY1pwaJlGkwjqUn8C1ovSffCog3MWYdqMPsn1IU11Z5242pwwVtO6h0DVWzrB2yr41aZqMz3c1yS+VHOqgqayCN5iWkAUZGcs4B3VdzH7s3VUDRSEZ9g0Bu3lQSYuf84dwDdtjHCJjYPmTPDJCvPBKssCGq2CntXSNsyfaGa5Y6f1mrxc/gc+oiyil97kAq3Nsr93LQL1kd+FRyzx1O0GI4GsRP5hHBxmzl6nJvUWq2GeMITD6Q3SS0i8pJn6RSs0WkhlYMxjd5gXkv+Mx7PeVicfHYQxRrw6vTDL38X+S35HsFOkLM6tS7WxBOzeT3/M6sotExZHYtINkkiLA6UpmbSG3gdS39okYFGrweQHKwpifZjqm5/Ny+1mBKZGrZTLGFuGktpzSQyKJSFPM0V75jAEjuWALV9uAIc9jxE+jpq0EpeGCYm9oGdh8x7Vjb14ab2May29B7HnSRT0Y87sosOZE8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
