travis:
  secure:
    BINSTAR_TOKEN: XDwGRIYbxih1k10BqOhIQLxPN98Y7Cd0YddlHhf3fTDj6K2Pml+7dUojIb4JF4F63DvL9U5tRSU+BDVxNBGeJGDVt9GHbhBVo/NdoN7/WxptUwzgKT84V7UsFbmp+WXPtw7F8zIM+4yvB5RUADVse4Z2bq77R8A+LnyWv0hFbfNvvhQIlTLo0RifMaK+oJY5albczEpotbVQFhJfEF5VRKNHhfZF5xim5WvEfaW5Hynq6Abmxoo4XXVJgMiEFNsSrG9sPLMEiMKsXQcjpRbZDjNMYntsKpbh+rVmXbK8+C196Nh6eXmUcZ2iSeCmAUnsSE4S8jMYHVuzCyHh/l8l0YbrTNZm/+VJ3Yd57+z1VM5+96/rQwoFDL3IpU7orRi+tNTL2edMqMiIxBWGF5kJHx92/YS/5Z/z5iwKauOov+CKitAuFddC50U1E3XNm7vxV8NKQUL0VGThoATWKNJv42l3wNvXFGYacF6fD/upe1OWsLuRZpzbhzJyNjtYbjvCe7B05lpnrrrylrUZsxWCLSyFDnghS3j00N0j1KAD6O4P750Lp7pVCHBiJpOwLVliumh564OGnxyuAI20SdAL9JZZbOvmDLPLrPaYFCiMxDW8mF5NyJgr1/CZrrw5qWSv57QLvmOi27SPKU4rWUnlfD890NkgV/A+p2diOuXOVuk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
