travis:
  secure:
    BINSTAR_TOKEN: C5/g8YFwlIWThTM0Eda1te1xBVsrIM47BXog9uMIX07ZiTYwhrXlKi5KMLJrgHNI23sJmQcCULMHUT1CiNAlyXXO31o1lwBuGtqG8IOIM1J2NAPjibxM8dSaLOdByc/KTb2LUOajer3cdw8fo4AAomdLMshqM1f25+4wsQXfBLvMGsZ9j6DRUthjvhlxfLxXpBRfnTUyxbRY83jKepn6Je30pauwC3vw3+wQ1gPeUzQV2UARGGwdl3WUaTaTK9wM1qfLWgAzuOhz4dUYd22km8b72laAqldZFIBQZP8HfkHg4tc2t9Cuxo+VD423WmOxlGObGOBFG1Vv3YrlbLiX4gc0o/BiCanAIPLN7lU12g2bXVuMNb5DbvJTy9E9zyGLKMTRwmWQ71Y4UjhQMdFV1tpZLHUbqf2Aj2IU3pY/5y3cLAmB4zgig1yCB7NqHxYmg0z9a2sC4ZkNiAzneVv8nu3THAkgo/Wbtv95ljlHXfRY79JV+mWUPLp4JvE511RoU9zSfT5XNwyAVSGk4RM1pO+c3/9B8wkDffEJHIZSIVH5bUyeErg6PRQbbfwh9nYh5g1DQKvYC9VJKaTK3tsZoLE++vrT7JbAHFF057jsby2LpPkwfHQx47GgYR4V33m7pRTgbHXS8E9fNn3xD0BILJdbe3WTRnrsajEqzjqoGos=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
