travis:
  secure:
    BINSTAR_TOKEN: gbVCcWshZwadwNYWI/pAbeMBJ7NUiGdgQdEEWc+b34UjPC+jTwQ5aF9u0vnsxOI123qwnvsLp8bsa6dYi+NRTwBD2hsGsLgjYcUmtk91rwdQNpGKgZ0ojlsF9Quqs9rVVN9zwarHh0mDTKeiLsm3xv/7h4ES7THTvNoe8FmVMIfKvVxCt7X77Bs6Xi/SdBB+y86tIBUSAuH+okosXjuPeKnmZpvI5vOpwGeP/cRiqWyYsZP9vhkYluzKG8ltctzwB5BNBDExGa6s6Q7e5MVgzJykRahadqOQ/87867w0Hhvgl6+Nfq8/QbntHyMShdozhpyfIxC2FkZ7LH4P/WiCFidIBM+/a4eCgsuJLkPFZhXZ2JsTgGfp6WIQmKo/Oz5ZWDdGS12NwUJ+/V78fOY+JxZcWcpRtZMf6FBYcKbvf8YJTlKsnSggAqmCGwvxOqFg1yO/BX5qUEB1Th8TUq9KkxVVbswSyXtrQgiE70dhG2sIX8yPDvFtpPN9vK40V2UFFsAp9Ami+YNkNPkHzLWWmRVpLcNoAGh3EbAArc38w09YMYlsSOOIaAB4yxzHshnnoVyDlzD6oJZ7qn/IE3wILgDxH91w5QdFNOg+OK0kGZ0uNlc6xXLd0QdR8yQMS64PNs+btJz/EmeF0ievNyyjeJDUi+ew1tEmipddXTZoAlI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
