travis:
  secure:
    BINSTAR_TOKEN: oPLKHmw70iTn3mP5JndLJg5tI+3mI4P56pzM6LPGEKcCYgpyiEE27p7wloMHnA1KdzrWS5uAiXHHMnl4uKZylH+nohyqOjMNdQqYvax2fOvOBOCH9L3bVVr1rPFhOUCAy7aeHVuQ0aRou8EzNa+A9srVxkCLNcy2d0g/Ik0pO/dvLPcgQ/MJSh2Y233WTW43RV3KjnswTMamq/7SMbYI3xlK84GIH9VMvIH+y/dJXq3cdyV/7L8HssVDaZuKfeo94iVAd1oI/qaF7BsmDwx6Bt5nyYNtd7fjmpIyXLoOyxp5vCpu0EcgpIn/Od0/YDOQt6oLG1NdX2YNY/jtC1cI4l6iP3xd78knN8L2hD59tAo1WFlaxEJxsgkWLiaLXfNVwU/ql/WvObDSobmKTOQNiR0IB+xBeVlJuPwxEg8kf6yM5iRTSZApo29n9nummxpbL3MDVLDWUsxcI4KwbjdHOFp8GMpEH8aktJfPB4aUvarXaosd08HjwoOr6++0Kpy5etCMRAqGheFJ2cMHTfua7QSRScTF9HpADPOKGxmqv8D/zy9c9/pvUQ/k3ZNKIq9pRi6AlRIjN3q293Q2zgyxRcKLOdjnD/FV0l3wjFK8bdkvBtd5p1fLTeULYFivHpACBGBNeiHefCHr0+kGlkYq+j4nvsZ1YrSJTwWvVV4qgUA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
